project:
  type: website

website:
  title: "PlanetSehlke"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: cv.html
        text: CV
      - href: publications.html
        text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
