project:
  output-dir: docs
  type: website

website:
  title: "PlanetSehlke"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: cv.html
        text: CV
      - href: publications.html
        text: Publications
      # - href: research.html
      #   text: Research
      # - href: test.html
      #   text: Test

format:
  html:
    theme: litera
    css: styles.css
    toc: true
