project:
  type: website

website:
  title: "PlanetSehlke"
  navbar:
    left:
      - href: /_site/index.html
        text: Home
      - href: /_site/cv.html
        text: CV
      - href: /_site/publications.html
        text: Publications
      - href: /_site/projects.html
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
